<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>解决回调地狱 - Promise</title>
</head>
<body>
    <p>then方法的第二个函数与.catch用法基本一致，但是catch方法可以捕捉then两个函数内部的错误信息</p>
    <ul>
        <li>pending: 初始状态，既不是成功，也不是失败状态。</li>
        <li>fulfilled: 意味着操作成功完成。</li>
        <li>rejected: 意味着操作失败。</li>
    </ul>
    <script>
        // 1.基本应用
        // var p1 = new Promise((resolve, reject) => {
        //     setTimeout(() => {
        //         resolve('成功');
        //         // reject('失败');
        //     }, 2000)
        // })
        // // 写法一
        // p1.then((res) => {
        //     // 返回resolve时执行
        //     console.log(res);
        // }, (err) => {
        //     // 返回reject时执行
        //     console.log(err);
        // })
        // 写法二
        // p1.then((res) => {
        //     // 返回resolve时执行
        //     console.log(res);
        // }).catch((err) => {
        //     // 返回resolve时执行
        //     console.log(err);
        // })


        // 2.链式调用 解决回调地狱的问题 Promise使代码更加简洁 流程清晰 易于理解
        var p1 = new Promise((resolve, reject) => {
            setTimeout(() => {
                console.log('p1');
                resolve('我是来自p1的参数');
            }, 2000)
        })

        var p2 = (param) => {
            return new Promise((resolve, reject) => {
                setTimeout(() => {
                    console.log('p2', param);
                    resolve('我是来自p2的参数');
                }, 1000)
            })
        }

        var p3 = (param) => {
            return new Promise((resolve, reject) => {
                setTimeout(() => {
                    console.log('p3', param);
                    resolve('我是来自p3的参数');
                }, 1000)
            })
        }

        p1.then(p2)
          .then(p3)
          .then((res) => {
            console.log('finished', res);
          })

        // 3.Promise的方法
        // var f1 = new Promise((resolve, reject) => {
        //     setTimeout(() => {
        //         console.log('f1');
        //         resolve('我是来自f1的参数');
        //     }, 2000)
        // })

        // var f2 = new Promise((resolve, reject) => {
        //     setTimeout(() => {
        //         console.log('f2');
        //         resolve('我是来自f2的参数');
        //     }, 1000)
        // })

        // var f3 = new Promise((resolve, reject) => {
        //     setTimeout(() => {
        //         console.log('f3');
        //         resolve('我是来自f3的参数');
        //     }, 1000)
        // })

        // Promise.all([f1, f2, f3]).then((res) => {
        //     console.log('all: 所有的promise对象都成功的时候才会触发成功，', res);
        // }).catch((err) => {
        //     console.log('all: 任意一个子promise被失败后触发', err);
        // })

        // Promise.race([f1, f2, f3]).then((res) => {
        //     console.log('race: 任意一个子promise被成功后触发', res);
        // }).catch((err) => {
        //     console.log('race: 任意一个子promise被失败后触发', err);
        // })
    </script>
</body>
</html>